version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install deps
          command: npm install
      - run:
          name: test
          command: npm test
  release:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release || true

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
