version: 2.1

jobs:
  install_deps:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - node_modules/*
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/project
      - run:
          name: test
          command: npm test
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/project
      - run: npm run build
      - run: npm run semantic-release || true

workflows:
  version: 2
  test_and_release:
    jobs:
      - install_deps
      - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - test
